# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Wei Heng
title: Sr Software Development Engineer
description: Mynux Engineer of day, Machine Learning Enthusiast at night.
email: to@hengwei.me
# email_title: Email (Email title override)
phone: +1 206-825-1616
# phone_title: Phone (Phone title override)
website: https://t.hengwei.me
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: lengrfulluse
github_username:  lengerfulluse
stackoverflow_username: lengerfulluse
linkedin_username: hengwei

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Mynux Engineer of day, Machine Learning Enthusiast at night.

  **The goal of life is to make your heartbeat match the beat of the universe,to match your nature with nature.**

content:
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Beijing University of Posts & Telecommunications
        sub_title: MS - Computer Science
        caption: 2011.9 - 2014.4
        quote: >

        description: | # this will include new lines to allow paragraphs
          Natural Language Processing & Machine Learning
      - layout: top-right
        title: Nanjing University of Posts & Telecommunications
        sub_title: BA - Management Information System
        caption: 2007.9 - 2011.6
        quote: >

        description: | # this will include new lines to allow paragraphs
          Information Management & Information System
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Amazon.com
        sub_title: Sr Software Development Engineer
        caption: Dec 2021 - present
        link:
        quote: >

        description: | # this will include new lines to allow paragraphs
          **Payments Processing**
      - layout: right
        title: Amazon.com
        sub_title: Software Development Engineer II
        caption: Sep 2017 - present
        link:
        quote: >

        description: | # this will include new lines to allow paragraphs
          **Payments Service**
      - layout: right
        title: Baidu.com
        sub_title: Sr Research & Development Engineer
        caption: Sep 2016 - Sep 2017
        link:
        quote: >

        description: | # this will include new lines to allow paragraphs
          **Advertising Platform**
           - (Phoenix Nest), feed stream oriented.
      - layout: right
        title: Amazon.cn
        sub_title: Software Development Engineer I
        caption: Apr 2014 - Sep 2016
        link:
        quote: >
        description: | # this will include new lines to allow paragraphs
          **Payments China**
            - To develop and maintain Payments Platform services for both China and Global business.
            Common used develop languages are java and perl/mason.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mynux
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
